import { NetflixAttribute } from "../types/netflix.type";

export const CARTOON_CARDS: Array<NetflixAttribute> = [
  { answer: "Wall-E" },
  { answer: "Rango" },
  { answer: "Winnie the Pooh" },
  { answer: "The Croods" },
  { answer: "Megamind" },
  { answer: "Cloudy with a Chance of Meatballs" },
  { answer: "Coraline" },
  { answer: "Bee Movie" },
  { answer: "Flushed Away" },
  { answer: "Happy Feet" },
  { answer: "Over the Hedge" },
  { answer: "Shark Tale" },
  { answer: "Surf's Up" },
  { answer: "Horton Hears a Who!" },
  { answer: "The Road to El Dorado" },
  { answer: "Chicken Run" },
  { answer: "Antz" },
  { answer: "The Wild Thornberrys Movie" },
  { answer: "Rugrats in Paris: The Movie" },
  { answer: "The SpongeBob SquarePants Movie" },
  { answer: "Ratatouille" },
  { answer: "Mulan" },
  { answer: "The Nightmare Before Christmas" },
  { answer: "The Lion King" },
  { answer: "Aladdin" },
  { answer: "Beauty and the Beast" },
  { answer: "Toy Story" },
  { answer: "Frozen" },
  { answer: "Finding Nemo" },
  { answer: "The Little Mermaid" },
  { answer: "Cinderella" },
  { answer: "Moana" },
  { answer: "Zootopia" },
  { answer: "Pocahontas" },
  { answer: "Hercules" },
  { answer: "Tarzan" },
  { answer: "Lilo & Stitch" },
  { answer: "Big Hero 6" },
  { answer: "Coco" },
  { answer: "Brave" },
  { answer: "Up" },
  { answer: "Wreck-It Ralph" },
  { answer: "Inside Out" },
  { answer: "Cars" },
  { answer: "The Jungle Book" },
  { answer: "Dumbo" },
  { answer: "Peter Pan" },
  { answer: "Shrek" },
  { answer: "Kung Fu Panda" },
  { answer: "How to Train Your Dragon" },
  { answer: "Madagascar" },
  { answer: "Ice Age" },
  { answer: "Despicable Me" },
  { answer: "Finding Dory" },
  { answer: "Monsters, Inc." },
  { answer: "The Lego Movie" },
  { answer: "Kung Fu Panda 3" },
  { answer: "How to Train Your Dragon: The Hidden World" },
  { answer: "The Princess and the Frog" },
  { answer: "Winnie the Pooh" },
  { answer: "The Croods" },
  { answer: "Megamind" },
  { answer: "Cloudy with a Chance of Meatballs" },
  { answer: "Coraline" },
  { answer: "Bee Movie" },
  { answer: "Flushed Away" },
  { answer: "Happy Feet" },
  { answer: "Over the Hedge" },
  { answer: "Surf's Up" },
  { answer: "Horton Hears a Who!" },
  { answer: "The Road to El Dorado" },
  { answer: "Chicken Run" },
  { answer: "Antz" },
  { answer: "The Wild Thornberrys Movie" },
  { answer: "Rugrats in Paris: The Movie" },
  { answer: "The SpongeBob SquarePants Movie" },
  { answer: "Ratatouille" },
  { answer: "Mulan" },
  { answer: "The Nightmare Before Christmas" },
  { answer: "Corpse Bride" },
  { answer: "The Incredibles" },
  { answer: "Kung Fu Panda 2" },
  { answer: "Shrek 2" },
  { answer: "Finding Nemo" },
  { answer: "Cars" },
  { answer: "Rango" },
  { answer: "The Lego Movie 2: The Second Part" },
  { answer: "The Secret Life of Pets" },
  { answer: "Moana" },
  { answer: "Trolls" },
  { answer: "Sing" },
  { answer: "Spider-Man: Into the Spider-Verse" },
  { answer: "The Boss Baby" },
  { answer: "Despicable Me 2" },
  { answer: "Brave" },
  { answer: "Tangled" },
  { answer: "Coco" },
  { answer: "Zootopia" },
  { answer: "Puss in Boots" },
  { answer: "Rise of the Guardians" },
  { answer: "The Book of Life" },
  { answer: "Kubo and the Two Strings" },
  { answer: "The Emoji Movie" },
  { answer: "Ferdinand" },
  { answer: "Isle of Dogs" },
  { answer: "Hotel Transylvania" },
  { answer: "The Lego Batman Movie" },
  { answer: "Wreck-It Ralph" },
  { answer: "The Good Dinosaur" },
  { answer: "Epic" },
  { answer: "Rio" },
  { answer: "Home" },
  { answer: "Storks" },
  { answer: "Smurfs: The Lost Village" },
  { answer: "The Star" },
  { answer: "Sherlock Gnomes" },
  { answer: "Smallfoot" },
  { answer: "Abominable" },
  { answer: "Onward" },
  { answer: "The Willoughbys" },
  { answer: "Soul" },
];

export const ACTION_CARDS: Array<NetflixAttribute> = [
  { answer: "Die Hard" },
  { answer: "Mad Max: Fury Road" },
  { answer: "The Dark Knight" },
  { answer: "Inception" },
  { answer: "John Wick" },
  { answer: "Gladiator" },
  { answer: "The Matrix" },
  { answer: "The Revenant" },
  { answer: "The Bourne Identity" },
  { answer: "Kill Bill: Vol. 1" },
  { answer: "The Equalizer" },
  { answer: "The Raid: Redemption" },
  { answer: "Casino Royale" },
  { answer: "Taken" },
  { answer: "Speed" },
  { answer: "Heat" },
  { answer: "The Italian Job" },
  { answer: "Crank" },
  { answer: "Skyfall" },
  { answer: "The Rock" },
  { answer: "Salt" },
  { answer: "The Fifth Element" },
  { answer: "Kingsman: The Secret Service" },
  { answer: "Ip Man" },
  { answer: "Dredd" },
  { answer: "Django Unchained" },
  { answer: "Warrior" },
  { answer: "Kick-Ass" },
  { answer: "Sicario" },
  { answer: "The Departed" },
  { answer: "The Accountant" },
  { answer: "Edge of Tomorrow" },
  { answer: "Black Hawk Down" },
  { answer: "I Am Legend" },
  { answer: "Drive" },
  { answer: "Atomic Blonde" },
  { answer: "The Town" },
  { answer: "The Mechanic" },
  { answer: "The Book of Eli" },
];

export const HORROR_CARDS: Array<NetflixAttribute> = [
  { answer: "The Shining" },
  { answer: "Get Out" },
  { answer: "A Nightmare on Elm Street" },
  { answer: "The Conjuring" },
  { answer: "Hereditary" },
  { answer: "The Exorcist" },
  { answer: "The Babadook" },
  { answer: "The Witch" },
  { answer: "Psycho" },
  { answer: "Cabin in the Woods" },
  { answer: "Sinister" },
  { answer: "It Follows" },
  { answer: "The Texas Chain Saw Massacre" },
  { answer: "Rosemary's Baby" },
  { answer: "Halloween" },
  { answer: "Saw" },
  { answer: "The Ring" },
  { answer: "Don't Breathe" },
  { answer: "The Sixth Sense" },
  { answer: "Paranormal Activity" },
  { answer: "Insidious" },
  { answer: "The Others" },
  { answer: "Crimson Peak" },
  { answer: "The Blair Witch Project" },
  { answer: "Annabelle" },
  { answer: "The Grudge" },
  { answer: "The Orphanage" },
  { answer: "The Descent" },
  { answer: "The Mist" },
  { answer: "The Omen" },
  { answer: "The Hills Have Eyes" },
  { answer: "The Evil Dead" },
  { answer: "The Haunting" },
  { answer: "The Amityville Horror" },
  { answer: "28 Days Later" },
  { answer: "The Poltergeist" },
  { answer: "Drag Me to Hell" },
  { answer: "A Quiet Place" },
  { answer: "Doctor Sleep" },
];

export const COMEDY_CARDS: Array<NetflixAttribute> = [
  { answer: "Superbad" },
  { answer: "Anchorman: The Legend of Ron Burgundy" },
  { answer: "Ferris Bueller's Day Off" },
  { answer: "The Grand Budapest Hotel" },
  { answer: "Airplane!" },
  { answer: "Dumb & Dumber" },
  {
    answer:
      "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
  },
  { answer: "Crazy, Stupid, Love." },
  { answer: "The 40-Year-Old Virgin" },
  { answer: "The Princess Bride" },
  { answer: "Groundhog Day" },
  { answer: "The Big Lebowski" },
  { answer: "Napoleon Dynamite" },
  { answer: "This Is Spinal Tap" },
  { answer: "The Hangover" },
  { answer: "Annie Hall" },
  { answer: "Fargo" },
  { answer: "Amélie" },
  { answer: "Raising Arizona" },
  { answer: "Hot Fuzz" },
  { answer: "Zoolander" },
  { answer: "Shaun of the Dead" },
  { answer: "The Breakfast Club" },
  { answer: "Office Space" },
  { answer: "Bridesmaids" },
  { answer: "Ghostbusters" },
  { answer: "The Royal Tenenbaums" },
  { answer: "Dazed and Confused" },
  { answer: "My Cousin Vinny" },
  { answer: "Tropic Thunder" },
  { answer: "Forrest Gump" },
  { answer: "Big" },
  { answer: "Zombieland" },
  { answer: "Super Troopers" },
  { answer: "The Office" },
  { answer: "The Waterboy" },
  { answer: "The Truman Show" },
  { answer: "Step Brothers" },
  { answer: "Hot Tub Time Machine" },
  { answer: "Pineapple Express" },
];
export const SCIFI_CARDS:Array<NetflixAttribute> = [
  {"answer": "Blade Runner"},
  {"answer": "The Matrix"},
  {"answer": "Inception"},
  {"answer": "The Terminator"},
  {"answer": "2001: A Space Odyssey"},
  {"answer": "Eternal Sunshine of the Spotless Mind"},
  {"answer": "District 9"},
  {"answer": "The Fifth Element"},
  {"answer": "Avatar"},
  {"answer": "The Day the Earth Stood Still"},
  {"answer": "Moon"},
  {"answer": "Ex Machina"},
  {"answer": "Donnie Darko"},
  {"answer": "Arrival"},
  {"answer": "Interstellar"},
  {"answer": "Close Encounters of the Third Kind"},
  {"answer": "A.I. Artificial Intelligence"},
  {"answer": "War of the Worlds"},
  {"answer": "Minority Report"},
  {"answer": "Metropolis"},
  {"answer": "Contact"},
  {"answer": "Children of Men"},
  {"answer": "The Martian"},
  {"answer": "The Hitchhiker's Guide to the Galaxy"},
  {"answer": "The Prestige"},
  {"answer": "Solaris"},
  {"answer": "Predator"},
  {"answer": "Looper"},
  {"answer": "The Abyss"},
  {"answer": "The Andromeda Strain"},
  {"answer": "The Truman Show"},
  {"answer": "The Island"},
  {"answer": "Prometheus"},
  {"answer": "The Time Machine"},
  {"answer": "Stalker"},
  {"answer": "The War of the Worlds"},
  {"answer": "Sunshine"},
  {"answer": "Snowpiercer"},
  {"answer": "The Fly"},
  {"answer": "The Host"},
  {"answer": "Primer"},
  {"answer": "The Adjustment Bureau"},
  {"answer": "Annihilation"},
  {"answer": "The Maze Runner"},
  {"answer": "Don't Let the Dead"},
  {"answer": "Cloud Atlas"},
  {"answer": "The Circle"},
  {"answer": "Cargo"},
  {"answer": "Moon"}
]

export const CRIME_SUSPENSE_CARDS: Array<NetflixAttribute> = [
  {"answer": "The Silence of the Lambs"},
  {"answer": "Se7en"},
  {"answer": "Shutter Island"},
  {"answer": "Gone Girl"},
  {"answer": "The Sixth Sense"},
  {"answer": "Prisoners"},
  {"answer": "Mystic River"},
  {"answer": "The Girl with the Dragon Tattoo"},
  {"answer": "Misery"},
  {"answer": "Cape Fear"},
  {"answer": "Zodiac"},
  {"answer": "The Others"},
  {"answer": "Panic Room"},
  {"answer": "Black Swan"},
  {"answer": "Side Effects"},
  {"answer": "The Game"},
  {"answer": "Secret Window"},
  {"answer": "The Machinist"},
  {"answer": "Flightplan"},
  {"answer": "The Prestige"},
  {"answer": "Crimson Peak"},
  {"answer": "Gone Baby Gone"},
  {"answer": "Primal Fear"},
  {"answer": "Don't Breathe"},
  {"answer": "Memento"},
  {"answer": "The Gift"},
  {"answer": "The Brave One"},
  {"answer": "Fractured"},
  {"answer": "The Call"},
  {"answer": "Cellular"},
  {"answer": "Red Eye"},
  {"answer": "88 Minutes"},
  {"answer": "The Taking of Pelham 123"},
  {"answer": "Flight"},
  {"answer": "The Interpreter"},
  {"answer": "The Next Three Days"},
  {"answer": "Arlington Road"},
  {"answer": "The Equalizer"},
  {"answer": "Copycat"},
  {"answer": "Phone Booth"},
  {"answer": "I Am Watching You"},
  {"answer": "The Vanishing"},
  {"answer": "Murder on the Orient Express"}
]


export const ENGLISH_CARDS: Array<NetflixAttribute> = CARTOON_CARDS
  .concat(ACTION_CARDS)
  .concat(HORROR_CARDS)
  .concat(COMEDY_CARDS)
  .concat(SCIFI_CARDS)
  .concat(CRIME_SUSPENSE_CARDS);
