import { NetflixAttribute } from "../types/netflix.type";

export const PINOY_CARDS: Array<NetflixAttribute> = [
  {"answer": "Heneral Luna"},
  {"answer": "BuyBust"},
  {"answer": "On the Job"},
  {"answer": "Four Sisters and a Wedding"},
  {"answer": "That Thing Called Tadhana"},
  {"answer": "One More Chance"},
  {"answer": "My Amnesia Girl"},
  {"answer": "Sana Maulit Muli"},
  {"answer": "Kita Kita"},
  {"answer": "The Hows of Us"},
  {"answer": "Hello, Love, Goodbye"},
  {"answer": "Seven Sundays"},
  {"answer": "Starting Over Again"},
  {"answer": "Sakaling Maging Tayo"},
  {"answer": "Hintayan ng Langit"},
  {"answer": "Ang Babaeng Allergic sa WiFi"},
  {"answer": "Babae at Baril"},
  {"answer": "Liway"},
  {"answer": "Patay na si Hesus"},
  {"answer": "Birdshot"},
  {"answer": "Kita-Kita"},
  {"answer": "Deadma Walking"},
  {"answer": "Die Beautiful"},
  {"answer": "Sid & Aya: Not a Love Story"},
  {"answer": "The Breakup Playlist"},
  {"answer": "Tadhana"},
  {"answer": "Culion"},
  {"answer": "Metro Manila"},
  {"answer": "Ang Panahon ng Halimaw"},
  {"answer": "Bwakaw"},
  {"answer": "Oda sa Wala"},
  {"answer": "Ma' Rosa"},
  {"answer": "Maria"},
  {"answer": "Isa Pa with Feelings"},
  {"answer": "BuyBust"},
  {"answer": "Sunday Beauty Queen"},
  {"answer": "Goyo: Ang Batang Heneral"},
  {"answer": "Honor Thy Father"},
  {"answer": "Bar Boys"},
  {"answer": "Kasal"},
  {"answer": "Through Night and Day"},
  {"answer": "Sid and Aya: Not a Love Story"},
  {"answer": "The Panti Sisters"},
  {"answer": "Hello, Pogi"},
  {"answer": "Clarita"},
  {"answer": "Hello, Stranger: The Movie"},
  {"answer": "Fan Girl"},
  {"answer": "Untrue"},
  {"answer": "He Who Is Without Sin"},
  {"answer": "John En Martian"}
]
;
