import { NetflixAttribute } from "../types/netflix.type";

export const ANIME_CARDS: Array<NetflixAttribute> = [
    {answer: "Naruto"},
    {answer: "Dragon Ball Z"},
    {answer: "One Piece"},
    {answer: "Death Note"},
    {answer: "My Hero Academia"},
    {answer: "Bleach"},
    {answer: "Hunter x Hunter"},
    {answer: "Tokyo Ghoul"},
    {answer: "Sword Art Online"},
    {answer: "Fairy Tail"},
    {answer: "One Punch Man"},
    {answer: "JoJo's Bizarre Adventure"},
    {answer: "Steins;Gate"},
    {answer: "Code Geass"},
    {answer: "Haikyuu!!"},
    {answer: "Demon Slayer: Kimetsu no Yaiba"},
    {answer: "Black Clover"},
    {answer: "The Promised Neverland"},
    {answer: "Dr. Stone"},
    {answer: "Violet Evergarden"},
    {answer: "Assassination Classroom"},
    {answer: "Black Lagoon"},
    {answer: "Parasyte: The Maxim"},
    {answer: "Death Parade"},
    {answer: "Mirai Nikki (Future Diary)"},
    {answer: "Gurren Lagann"},
    {answer: "No Game No Life"},
    {answer: "KonoSuba: God's Blessing on This Wonderful World!"},
    {answer: "Re:Zero - Starting Life in Another World"},
    {answer: "The Rising of the Shield Hero"},
    {answer: "Vinland Saga"},
    {answer: "Fire Force"},
    {answer: "Dragon Ball"},
    {answer: "Death Note: The Last Name"},
    {answer: "Cowboy Bebop"},
    {answer: "Neon Genesis Evangelion"},
    {answer: "Hunter x Hunter"},
    {answer: "Card Captor Sakura"},
    {answer: "Zom 100: Bucket List of the Dead"},
    {answer: "Baki The Grappler"},
    {answer: "Knock-Out"},
    {answer: "Mushoku Tensei"},
    {answer: "Overlord"},
    {answer: "Inuyasha"},
    {answer: "Yu-Gi-Oh"},
    {answer: "The Rising of Shield Hero"}
]
