import { NetflixAttribute } from "../types/netflix.type";

export const DISNEY_CARDS: Array<NetflixAttribute> = [
    {"answer": "Wall-E"},
    {"answer": "Rango"},
    {"answer": "Winnie the Pooh"},
    {"answer": "The Croods"},
    {"answer": "Megamind"},
    {"answer": "Cloudy with a Chance of Meatballs"},
    {"answer": "Coraline"},
    {"answer": "Bee Movie"},
    {"answer": "Flushed Away"},
    {"answer": "Happy Feet"},
    {"answer": "Over the Hedge"},
    {"answer": "Shark Tale"},
    {"answer": "Surf's Up"},
    {"answer": "Horton Hears a Who!"},
    {"answer": "The Road to El Dorado"},
    {"answer": "Chicken Run"},
    {"answer": "Antz"},
    {"answer": "The Wild Thornberrys Movie"},
    {"answer": "Rugrats in Paris: The Movie"},
    {"answer": "The SpongeBob SquarePants Movie"},
    {"answer": "WALL·E"},
    {"answer": "Ratatouille"},
    {"answer": "Tangled"},
    {"answer": "Mulan"},
    {"answer": "The Nightmare Before Christmas"},
    {"answer": "Flushed Away"},
    {"answer": "Happy Feet"},
    {"answer": "Shark Tale"},
    {"answer": "Surf's Up"},
    {"answer": "Horton Hears a Who!"},
    {"answer": "The Road to El Dorado"},
    {"answer": "Chicken Run"},
    {"answer": "Antz"},
    {"answer": "The Wild Thornberrys Movie"},
    {"answer": "Rugrats in Paris: The Movie"},
    {"answer": "The SpongeBob SquarePants Movie"},
    {"answer": "WALL·E"},
    {"answer": "Ratatouille"},
    {"answer": "Tangled"},
    {"answer": "Mulan"},
    {"answer": "The Lion King"},
    {"answer": "Aladdin"},
    {"answer": "Beauty and the Beast"},
    {"answer": "Toy Story"},
    {"answer": "Frozen"},
    {"answer": "Finding Nemo"},
    {"answer": "The Little Mermaid"},
    {"answer": "Cinderella"},
    {"answer": "Moana"},
    {"answer": "Zootopia"},
    {"answer": "Pocahontas"},
    {"answer": "The Princess and the Frog"},
    {"answer": "Hercules"},
    {"answer": "Tarzan"},
    {"answer": "Lilo & Stitch"},
    {"answer": "Big Hero 6"},
    {"answer": "Coco"},
    {"answer": "Brave"},
    {"answer": "Up"},
    {"answer": "Wreck-It Ralph"},
    {"answer": "Inside Out"},
    {"answer": "Cars"},
    {"answer": "The Jungle Book"},
    {"answer": "Dumbo"},
    {"answer": "Peter Pan"},
    {"answer": "Wall-E"},
    {"answer": "Rango"},
    {"answer": "Winnie the Pooh"},
    {"answer": "The Croods"},
    {"answer": "Megamind"},
    {"answer": "Cloudy with a Chance of Meatballs"},
    {"answer": "Coraline"},
    {"answer": "Bee Movie"},
    {"answer": "Flushed Away"},
    {"answer": "Happy Feet"},
    {"answer": "Over the Hedge"},
    {"answer": "Shark Tale"},
    {"answer": "Surf's Up"},
    {"answer": "Horton Hears a Who!"},
    {"answer": "The Road to El Dorado"},
    {"answer": "Chicken Run"},
    {"answer": "Antz"},
    {"answer": "The Wild Thornberrys Movie"},
    {"answer": "Rugrats in Paris: The Movie"},
    {"answer": "The SpongeBob SquarePants Movie"},
    {"answer": "Ratatouille"},
    {"answer": "Mulan"},
    {"answer": "The Nightmare Before Christmas"},
    {"answer": "The Lion King"},
    {"answer": "Aladdin"},
    {"answer": "Beauty and the Beast"},
    {"answer": "Toy Story"},
    {"answer": "Frozen"},
    {"answer": "Finding Nemo"},
    {"answer": "The Little Mermaid"},
    {"answer": "Cinderella"},
    {"answer": "Moana"},
    {"answer": "Zootopia"},
    {"answer": "Pocahontas"},
    {"answer": "Hercules"},
    {"answer": "Tarzan"},
    {"answer": "Lilo & Stitch"},
    {"answer": "Big Hero 6"},
    {"answer": "Coco"},
    {"answer": "Brave"},
    {"answer": "Up"},
    {"answer": "Wreck-It Ralph"},
    {"answer": "Inside Out"},
    {"answer": "Cars"},
    {"answer": "The Jungle Book"},
    {"answer": "Dumbo"},
    {"answer": "Peter Pan"}
  ]
  
;
