import { NetflixAttribute } from "../types/netflix.type";

export const DISNEY_CARDS: Array<NetflixAttribute> = [
    {"answer": "The Lion King"},
    {"answer": "Aladdin"},
    {"answer": "Beauty and the Beast"},
    {"answer": "Toy Story"},
    {"answer": "Frozen"},
    {"answer": "Finding Nemo"},
    {"answer": "The Little Mermaid"},
    {"answer": "Cinderella"},
    {"answer": "Moana"},
    {"answer": "Zootopia"},
    {"answer": "Tangled"},
    {"answer": "Pocahontas"},
    {"answer": "Mulan"},
    {"answer": "Hercules"},
    {"answer": "Tarzan"},
    {"answer": "Lilo & Stitch"},
    {"answer": "Big Hero 6"},
    {"answer": "Coco"},
    {"answer": "Brave"},
    {"answer": "Ratatouille"},
    {"answer": "Up"},
    {"answer": "Wreck-It Ralph"},
    {"answer": "The Incredibles"},
    {"answer": "Inside Out"},
    {"answer": "Cars"},
    {"answer": "The Jungle Book"},
    {"answer": "Dumbo"},
    {"answer": "Peter Pan"},
    {"answer": "Sleeping Beauty"},
    {"answer": "Snow White and the Seven Dwarfs"},
    {"answer": "Robin Hood"},
    {"answer": "The Sword in the Stone"},
    {"answer": "The Rescuers"},
    {"answer": "The Fox and the Hound"},
    {"answer": "The Great Mouse Detective"},
    {"answer": "Oliver & Company"},
    {"answer": "The Aristocats"},
    {"answer": "The Emperor's New Groove"},
    {"answer": "The Black Cauldron"},
    {"answer": "The Adventures of Ichabod and Mr. Toad"},
    {"answer": "Alice in Wonderland"},
    {"answer": "The Many Adventures of Winnie the Pooh"},
    {"answer": "DuckTales the Movie: Treasure of the Lost Lamp"},
    {"answer": "Anastasia"},
    {"answer": "FernGully: The Last Rainforest"},
    {"answer": "The Land Before Time"},
    {"answer": "The Prince of Egypt"}
  ]  
;
