import { NetflixAttribute } from "../types/netflix.type";

export const ENGLISH_CARDS: Array<NetflixAttribute> = [
  {"answer": "Jurassic Park"},
  {"answer": "The Shawshank Redemption"},
  {"answer": "Pulp Fiction"},
  {"answer": "Forrest Gump"},
  {"answer": "Inception"},
  {"answer": "The Matrix"},
  {"answer": "The Dark Knight"},
  {"answer": "The Lord of the Rings: The Fellowship of the Ring"},
  {"answer": "The Godfather"},
  {"answer": "Avatar"},
  {"answer": "Gladiator"},
  {"answer": "Titanic"},
  {"answer": "The Lion King"},
  {"answer": "Interstellar"},
  {"answer": "The Silence of the Lambs"},
  {"answer": "E.T. the Extra-Terrestrial"},
  {"answer": "Schindler's List"},
  {"answer": "Fight Club"},
  {"answer": "The Princess Bride"},
  {"answer": "The Shining"},
  {"answer": "The Terminator"},
  {"answer": "Die Hard"},
  {"answer": "Blade Runner"},
  {"answer": "Memento"},
  {"answer": "The Big Lebowski"},
  {"answer": "American Beauty"},
  {"answer": "Inglourious Basterds"},
  {"answer": "The Social Network"},
  {"answer": "The Departed"},
  {"answer": "A Beautiful Mind"},
  {"answer": "Good Will Hunting"},
  {"answer": "The Sixth Sense"},
  {"answer": "Forrest Gump"},
  {"answer": "The Green Mile"},
  {"answer": "Gladiator"},
  {"answer": "Braveheart"},
  {"answer": "Forrest Gump"},
  {"answer": "The Matrix"},
  {"answer": "The Dark Knight"},
  {"answer": "The Godfather"},
  {"answer": "Pulp Fiction"},
  {"answer": "Inception"},
  {"answer": "Schindler's List"},
  {"answer": "Interstellar"},
  {"answer": "E.T. the Extra-Terrestrial"},
  {"answer": "The Lion King"},
  {"answer": "The Silence of the Lambs"},
  {"answer": "The Shawshank Redemption"},
  {"answer": "Avatar"},
  {"answer": "The Lion King"},
  {"answer": "Aladdin"},
  {"answer": "Beauty and the Beast"},
  {"answer": "Toy Story"},
  {"answer": "Frozen"},
  {"answer": "Finding Nemo"},
  {"answer": "The Little Mermaid"},
  {"answer": "Cinderella"},
  {"answer": "Moana"},
  {"answer": "Zootopia"},
  {"answer": "Tangled"},
  {"answer": "Pocahontas"},
  {"answer": "The Princess and the Frog"},
  {"answer": "Mulan"},
  {"answer": "Hercules"},
  {"answer": "Tarzan"},
  {"answer": "Lilo & Stitch"},
  {"answer": "Big Hero 6"},
  {"answer": "Coco"},
  {"answer": "Brave"},
  {"answer": "Ratatouille"},
  {"answer": "Up"},
  {"answer": "Wreck-It Ralph"},
  {"answer": "The Incredibles"},
  {"answer": "Inside Out"},
  {"answer": "Cars"},
  {"answer": "The Jungle Book"},
  {"answer": "Dumbo"},
  {"answer": "Peter Pan"},
  {"answer": "Sleeping Beauty"},
  {"answer": "Snow White and the Seven Dwarfs"},
  {"answer": "Robin Hood"},
  {"answer": "The Sword in the Stone"},
  {"answer": "The Rescuers"},
  {"answer": "The Fox and the Hound"},
  {"answer": "The Great Mouse Detective"},
  {"answer": "Oliver & Company"},
  {"answer": "The Little Mermaid II: Return to the Sea"},
  {"answer": "The Princess and the Frog"},
  {"answer": "The Aristocats"},
  {"answer": "The Emperor's New Groove"},
  {"answer": "Hercules"},
  {"answer": "Mulan"},
  {"answer": "Tarzan"},
  {"answer": "The Jungle Book"},
  {"answer": "Peter Pan"},
  {"answer": "Robin Hood"},
  {"answer": "The Sword in the Stone"}
]
;
