import { TabooAttribute, TabooDifficultyColor } from "./types/taboo.type";

export const TABOO_CARDS: Array<TabooAttribute> = [
  {
    answer: "AlDub",
    taboos: [
      "Alden Richards",
      "Maine Mendoza",
      "Kalyeserye",
      "Love Team",
      "Eat Bulaga!",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Wowowin",
    taboos: [
      "Willie Revillame",
      "Game Show",
      "GMA Network",
      "Cash Prize",
      "Contestants",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "It's Showtime",
    taboos: [
      "ABS-CBN",
      "Vice Ganda",
      "Anne Curtis",
      "Noontime Show",
      "Competition",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Liza Soberano",
    taboos: ["Actress", "Endorsements", "Enrique Gil", "Darna", "LizQuen"],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Eat Bulaga!",
    taboos: ["Noontime Show", "Dabarkads", "Lola Nidora", "Kalyeserye", "TVJ"],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Manny Pacquiao",
    taboos: [
      "Boxing Champion",
      "Politician",
      "Pac-Man",
      "Pacquiao vs. Mayweather",
      "Sarangani",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "KathNiel",
    taboos: [
      "Kathryn Bernardo",
      "Daniel Padilla",
      "Love Team",
      "Movies",
      "Fans",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Viral",
    taboos: [
      "Trending",
      "Social Media",
      "Viral Video",
      "Internet",
      "Online Fame",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "K-Pop",
    taboos: ["BTS", "Blackpink", "Idols", "Korean Music", "Fandom"],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "TikTok",
    taboos: [
      "Short Videos",
      "Social Media App",
      "Dances",
      "Viral Challenges",
      "ByteDance",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "PBB (Pinoy Big Brother)",
    taboos: [
      "Reality Show",
      "Housemates",
      "Big Brother",
      "ABS-CBN",
      "Confession Room",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Coco Martin",
    taboos: [
      "Actor",
      "FPJ's Ang Probinsyano",
      "Cardo Dalisay",
      "Endorsements",
      "Ang Panday",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Vice Ganda",
    taboos: [
      "Comedian",
      "Showtime",
      "Unkabogable",
      "Gandang Gabi Vice",
      "It's Showtime",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "MayWard",
    taboos: [
      "Maymay Entrata",
      "Edward Barber",
      "Love Team",
      "PBB",
      "Kapamilya",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Alden Richards",
    taboos: [
      "Actor",
      "GMA Network",
      "Eat Bulaga!",
      "Love Team",
      "Hello, Love, Goodbye",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "JaDine",
    taboos: [
      "James Reid",
      "Nadine Lustre",
      "Love Team",
      "On The Wings of Love",
      "Partnership",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Kapamilya",
    taboos: [
      "ABS-CBN",
      "TV Network",
      "Teleseryes",
      "Talent Show",
      "GMA vs. ABS-CBN",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Kapuso",
    taboos: [
      "GMA Network",
      "TV Network",
      "Kapuso vs. Kapamilya",
      "Teleseryes",
      "News",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "LizQuen",
    taboos: [
      "Liza Soberano",
      "Enrique Gil",
      "Love Team",
      "Dolce Amore",
      "Forevermore",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "GMA Network",
    taboos: [
      "Kapuso",
      "TV Network",
      "Kapuso vs. Kapamilya",
      "News",
      "Entertainment",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Adobo",
    taboos: ["Chicken", "Pork", "Vinegar", "Soy Sauce", "Filipino Dish"],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Sinigang",
    taboos: ["Tamarind", "Sour Soup", "Shrimp", "Pork", "Vegetables"],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Lechon",
    taboos: [
      "Roast Pig",
      "Crispy Skin",
      "Fiesta",
      "Philippine Cuisine",
      "Suckling Pig",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Kare-Kare",
    taboos: [
      "Oxtail",
      "Peanut Sauce",
      "Vegetables",
      "Filipino Stew",
      "Bagoong",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Pancit Canton",
    taboos: [
      "Stir-Fried Noodles",
      "Soy Sauce",
      "Chop Suey",
      "Cantonese Influence",
      "Filipino Noodles",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Balut",
    taboos: [
      "Duck Embryo",
      "Street Food",
      "Boiled Egg",
      "Unfertilized Egg",
      "Philippine Snack",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Taho",
    taboos: [
      "Soybean Curd",
      "Syrup",
      "Sago Pearls",
      "Street Food",
      "Philippine Snack",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Bicol Express",
    taboos: [
      "Spicy Dish",
      "Coconut Milk",
      "Chili Peppers",
      "Bicol Region",
      "Filipino Cuisine",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Halo-Halo",
    taboos: [
      "Mixed Dessert",
      "Shaved Ice",
      "Ube",
      "Leche Flan",
      "Tropical Fruits",
    ],
    difficultyColor: TabooDifficultyColor.EASY,
  },
  {
    answer: "Bibingka",
    taboos: [
      "Rice Cake",
      "Coconut",
      "Salted Egg",
      "Christmas Tradition",
      "Filipino Dessert",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Laing",
    taboos: [
      "Dried Taro Leaves",
      "Coconut Milk",
      "Chili Peppers",
      "Bicol Region",
      "Filipino Dish",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Sisig",
    taboos: [
      "Pig's Face",
      "Onions",
      "Sizzling Plate",
      "Pampanga Cuisine",
      "Filipino Dish",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Turon",
    taboos: [
      "Banana Spring Rolls",
      "Brown Sugar",
      "Lumpia Wrapper",
      "Deep-Fried",
      "Filipino Snack",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Kinilaw",
    taboos: [
      "Raw Fish Salad",
      "Vinegar",
      "Chili Peppers",
      "Ceviche",
      "Filipino Cuisine",
    ],
    difficultyColor: TabooDifficultyColor.HARD,
  },
  {
    answer: "Kakanin",
    taboos: [
      "Sticky Rice Dessert",
      "Coconut",
      "Kakanin Stall",
      "Suman",
      "Filipino Delicacy",
    ],
    difficultyColor: TabooDifficultyColor.HARD,
  },
  {
    answer: "Longganisa",
    taboos: [
      "Filipino Sausage",
      "Garlic",
      "Regional Variations",
      "Breakfast",
      "Pinoy Delight",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
  {
    answer: "Adidas",
    taboos: [
      "Street Food",
      "Grilled Chicken Feet",
      "BBQ Stalls",
      "Pinoy Delight",
      "Skewers",
    ],
    difficultyColor: TabooDifficultyColor.HARD,
  },
  {
    answer: "Kwek-Kwek",
    taboos: [
      "Quail Eggs",
      "Orange Batter",
      "Street Food",
      "Pinoy Snack",
      "Deep-Fried",
    ],
    difficultyColor: TabooDifficultyColor.HARD,
  },
  {
    answer: "Balikbayan Box",
    taboos: [
      "Overseas Filipino",
      "Package",
      "Pasalubong",
      "OFW Tradition",
      "Homecoming",
    ],
    difficultyColor: TabooDifficultyColor.MEDIUM,
  },
];
